//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by S3Controller.rc
//
#define IDD_S3CONTROLLER_DIALOG         102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDB_TX_SEL_INACT_BITMAP         129
#define IDB_TX_SEL_ACT_BITMAP           131
#define IDB_TX_UNSEL_INACT_BITMAP       132
#define IDB_TX_UNSEL_ACT_BITMAP         133
#define IDB_RX_MAIN_BITMAP              134
#define IDB_FOL_BITMAP                  135
#define IDB_FOL_DARK_BITMAP             136
#define IDD_SCROLLABLE_DIALOG           140
#define IDB_TX_UNSEL_IP_ACT_BITMAP      141
#define IDB_TX_UNSEL_IP_INACT_BITMAP    142
#define IDB_BITMAP3                     143
#define IDB_SPARE4_BITMAP               144
#define IDD_SYSTEM_MON_DIALOG           150
#define IDB_RX_MAIN_EMPTY_BITMAP        169
#define IDD_FACTORY_DIALOG              172
#define IDB_CHARGING_BITMAP             178
#define IDB_SETTINGS_BITMAP             179
#define IDB_RX_BACK_BTN_BITMAP          180
#define IDB_RX_MAIN_RX2_BITMAP          181
#define IDB_SHUTDOWN_BITMAP             183
#define IDB_TX_SEL_IP_ACT_BITMAP        184
#define IDB_TX_SEL_IP_INACT_BITMAP      185
#define IDB_TX_SEL_IP_ACT_ALRM_BITMAP   186
#define IDB_TX_SEL_IP_INACT_ALRM_BITMAP 187
#define IDB_TX_UNSEL_IP_ACT_ALRM_BITMAP 188
#define IDB_TX_UNSEL_IP_INACT_ALRM_BITMAP 189
#define IDB_TX_SEL_BATT_INVALID_BITMAP  190
#define IDB_TX_UNSEL_BATT_INVALID_BITMAP 191
#define IDB_TXTX_BATT_HOT_BITMAP        192
#define IDB_TXTX_BATT_COLD_BITMAP       193
#define IDB_TX_SEL_SLEEP_BITMAP         194
#define IDB_TX_UNSEL_SLEEP_BITMAP       195
#define IDR_TEST_MENU                   198
#define IDB_TX_LRG_ALARM_BITMAP         200
#define IDB_TXBATT1RV_BITMAP            201
#define IDB_TXBATT2V_BITMAP             202
#define IDB_TXBATT3V_BITMAP             203
#define IDB_TXBATT4V_BITMAP             204
#define IDB_TXBATT5V_BITMAP             205
#define IDB_TXBATT1RUV_BITMAP           206
#define IDB_TXBATT2UV_BITMAP            207
#define IDB_TXBATT3UV_BITMAP            208
#define IDB_TXBATT4UV_BITMAP            209
#define IDB_TXBATT5UV_BITMAP            210
#define IDB_TX_SML_ALARM_BITMAP         212
#define IDB_RED_LED_BITMAP              214
#define IDB_BLK_LED_BITMAP              215
#define IDB_GRN_LED_BITMAP              216
#define IDB_CH_BATT_EXCLAM_BITMAP       220
#define IDB_CH_BATT_FAIL_BITMAP         221
#define IDB_TXBATT1AV_BITMAP            222
#define IDB_TXBATT1AUV_BITMAP           223
#define IDB_INFO_BUTTON_BITMAP          224
#define IDB_TX_LRG_EMPTY_BITMAP         225
#define IDB_TX_SML_EMPTY_BITMAP         226
#define IDB_INFO_BUTTON_GREY_BITMAP     227
#define IDB_BLUE_BUTTON_BITMAP          228
#define IDB_BOOT_PPM_BITMAP             229
#define IDB_RX1_RLL5_ON_BITMAP          230
#define IDB_RX1_RLL4_ON_BITMAP          231
#define IDB_RX1_RLL3_ON_BITMAP          232
#define IDB_RX1_RLL2_ON_BITMAP          233
#define IDB_RX1_RLL1_ON_BITMAP          234
#define IDB_RX2_RLL5_ON_BITMAP          235
#define IDB_RX2_RLL4_ON_BITMAP          236
#define IDB_RX2_RLL3_ON_BITMAP          237
#define IDB_RX2_RLL2_ON_BITMAP          238
#define IDB_RX2_RLL1_ON_BITMAP          239
#define IDB_RX1_RLL5_RED_BITMAP         241
#define IDB_RX1_RLL1_RED_BITMAP         242
#define IDB_RX2_RLL5_RED_BITMAP         243
#define IDB_RX2_RLL1_RED_BITMAP         244
#define IDB_PPMBG_BITMAP                245
#define IDB_RX_EMPTY_BAR_BITMAP         246
#define IDB_TXBATT1GV_BITMAP            248
#define IDB_TXBATT1GUV_BITMAP           249
#define IDB_SYS_WARN_BITMAP             250
#define IDB_SYS_ERROR_BITMAP            251
#define IDB_SYS_INFO_BITMAP             252
#define IDC_CONTROLLER_HIERARCHY_TREE   1000
#define IDC_CONFIG_TAB                  1001
#define IDC_MAIN_TAB                    1001
#define IDC_ALARMS_BUTTON               1005
#define IDC_SYSTEM_GROUP                1006
#define IDC_SYSTEM_GRP                  1006
#define IDC_IP_GRP                      1007
#define IDC_TX_GRP                      1008
#define IDC_RX_GRP                      1009
#define IDC_TEST_BUTTON                 1010
#define IDC_SAVE_BUTTON                 1011
#define IDC_LOAD_BUTTON                 1012
#define IDC_IP_NODE_NAME_STATIC         1028
#define IDC_APPLY_BUTTON                1035
#define IDC_DISCARD_BUTTON              1036
#define IDC_RX_NODE_NAME_STATIC         1050
#define IDC_RX_SERIAL_NUM_STATIC        1051
#define IDC_SYS_INTGRTR_CHECK           1055
#define IDC_SYS_INTGRTR_TCONST_CHECK    1059
#define IDC_SYS_NODE_NAME_STATIC        1065
#define IDC_TX_NODE_NAME_STATIC         1079
#define IDC_SYS_MODEL_ID_STATIC         1200
#define IDC_PUSH_BUTTON                 1203
#define IDC_RX_FW_DATE_STATIC           1504
#define IDC_TX_FW_DATE_STATIC           1511
#define IDC_IPADDR_STATIC               1521
#define IDC_SYS_DATE_STATIC             1526
#define IDC_SYS_TIME_STATIC             1527
#define IDC_SYS_SNMP_TRAPS_STATIC       1534
#define IDC_ALARM_TRIG_BUTTON           1535
#define IDC_GDI_STATIC                  1546
#define IDC_INCOMING_MSG_STATIC         1560
#define IDC_IP_ADDR_EDIT                1561
#define IDC_MAX_STATIC                  1562
#define IDC_MIN_VALUE_STATIC            1563
#define IDC_IP_TEST_SIGNAL_CHECK        1568
#define IDC_TX_TEST_SIGNAL_CHECK        1569
#define IDC_SYS_MIN_LABEL_STATIC        1574
#define IDC_NODE_TITLE_STATIC           1575
#define IDC_DATETIME_STATIC             1576
#define IDC_RESET_BUTTON                1592
#define IDC_ALL_EVENTS_STATIC           1605
#define S3GDI_TEXT_EDIT                 1627
#define S3GDI_NUM_EDIT                  1628
#define S3GDI_CB                        1629
#define S3GDI_NUM2_EDIT                 1630
#define IDC_RX_CAL_EDIT                 1635
#define IDC_RX_CAL_STATIC               1636
#define IDC_TX_CAL_STATIC               1637
#define IDC_TX_CAL_EDIT                 1638
#define S3GDI_TIME_EDIT                 1639
#define IDC_TX_OPT_CAL_STATIC           1639
#define S3GDI_DATE_EDIT                 1640
#define IDC_TX_OPT_CAL_EDIT             1640
#define IDC_RF_PATH_COMBO               1641
#define IDC_GAIN_PATH_STATIC            1642
#define IDC_CAL_SET_BUTTON              1643
#define IDC_RX_CAL_SET_BUTTON           1644
#define IDC_TX_MSG_STATIC               1645
#define IDC_RX_MSG_STATIC               1646
#define IDC_SCRN_OFFSET_X_EDIT          1647
#define IDC_SCRN_OFFSET_Y_EDIT          1648
#define IDC_SCREEN_OFFSET_STATIC        1649
#define IDC_SCRN_OFFSET_SET_BUTTON      1650
#define IDC_STATUS_MSG_STATIC           1651
#define IDC_FACT_SN_STATIC              1652
#define IDC_FACT_SN_EDIT                1653
#define IDC_FACT_SN_SET_BUTTON          1654
#define IDC_TX_OPT_CAL_SET_BUTTON       1655
#define IDC_FACT_PN_STATIC              1656
#define IDC_FACT_PN_EDIT                1657
#define IDC_FACT_PN_SET_BUTTON          1658
#define IDC_CAL_GROUP_STATIC            1659
#define IDC_SYSTEM_GRP_STATIC           1660
#define ID_ONE_TWO                      32775
#define ID_ONE_THREE                    32776
#define ID_TEST_MENU                    32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        253
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1662
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
