//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by S3Agent.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_S3AGENT_DIALOG              102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_TEXT_IP_DIALOG              104
#define IDI_ICON2                       127
#define IDI_ICON1                       128
#define IDR_MENU1                       129
#define IDB_BITMAP1                     135
#define IDB_LOGO_PPM_TEST               135
#define IDB_TX_SEL_INACT_BITMAP         150
#define IDB_TX_SEL_ACT_BITMAP           151
#define IDB_TX_UNSEL_INACT_BITMAP       152
#define IDB_TX_UNSEL_ACT_BITMAP         153
#define IDB_RX_MAIN_BITMAP              154
#define IDB_FOL_BITMAP                  155
#define IDB_FOL_DARK_BITMAP             156
#define IDB_TX_UNSEL_IP_ACT_BITMAP      157
#define IDB_TX_UNSEL_IP_INACT_BITMAP    158
#define IDB_BITMAP3                     159
#define IDB_SPARE4_BITMAP               160
#define IDB_RX_MAIN_EMPTY_BITMAP        161
#define IDB_CHARGING_BITMAP             162
#define IDB_SETTINGS_BITMAP             163
#define IDB_RX_BACK_BTN_BITMAP          164
#define IDB_RX_MAIN_RX2_BITMAP          165
#define IDB_SHUTDOWN_BITMAP             166
#define IDB_TX_SEL_IP_ACT_BITMAP        167
#define IDB_TX_SEL_IP_INACT_BITMAP      168
#define IDB_TX_SEL_IP_ACT_ALRM_BITMAP   169
#define IDB_TX_SEL_IP_INACT_ALRM_BITMAP 170
#define IDB_TX_UNSEL_IP_ACT_ALRM_BITMAP 171
#define IDB_TX_UNSEL_IP_INACT_ALRM_BITMAP 172
#define IDB_TX_SEL_BATT_INVALID_BITMAP  173
#define IDB_TX_UNSEL_BATT_INVALID_BITMAP 174
#define IDB_TXTX_BATT_HOT_BITMAP        175
#define IDB_TXTX_BATT_COLD_BITMAP       176
#define IDB_TX_SEL_SLEEP_BITMAP         177
#define IDB_TX_UNSEL_SLEEP_BITMAP       178
#define IDB_TX_LRG_ALARM_BITMAP         179
#define IDB_TXBATT1RV_BITMAP            180
#define IDB_TXBATT2V_BITMAP             181
#define IDB_TXBATT3V_BITMAP             182
#define IDB_TXBATT4V_BITMAP             183
#define IDB_TXBATT5V_BITMAP             184
#define IDB_TXBATT1RUV_BITMAP           185
#define IDB_TXBATT2UV_BITMAP            186
#define IDB_TXBATT3UV_BITMAP            187
#define IDB_TXBATT4UV_BITMAP            188
#define IDB_TXBATT5UV_BITMAP            189
#define IDB_TX_SML_ALARM_BITMAP         190
#define IDB_RED_LED_BITMAP              191
#define IDB_BLK_LED_BITMAP              192
#define IDB_GRN_LED_BITMAP              193
#define IDB_CH_BATT_EXCLAM_BITMAP       194
#define IDB_CH_BATT_FAIL_BITMAP         195
#define IDB_TXBATT1AV_BITMAP            196
#define IDB_TXBATT1AUV_BITMAP           197
#define IDB_INFO_BUTTON_BITMAP          198
#define IDB_TX_LRG_EMPTY_BITMAP         199
#define IDB_TX_SML_EMPTY_BITMAP         200
#define IDB_INFO_BUTTON_GREY_BITMAP     201
#define IDB_BLUE_BUTTON_BITMAP          202
#define IDB_BOOT_PPM_BITMAP             203
#define IDB_RX1_RLL5_ON_BITMAP          204
#define IDB_RX1_RLL4_ON_BITMAP          205
#define IDB_RX1_RLL3_ON_BITMAP          206
#define IDB_RX1_RLL2_ON_BITMAP          207
#define IDB_RX1_RLL1_ON_BITMAP          208
#define IDB_RX2_RLL5_ON_BITMAP          209
#define IDB_RX2_RLL4_ON_BITMAP          210
#define IDB_RX2_RLL3_ON_BITMAP          211
#define IDB_RX2_RLL2_ON_BITMAP          212
#define IDB_RX2_RLL1_ON_BITMAP          213
#define IDB_RX1_RLL5_RED_BITMAP         214
#define IDB_RX1_RLL1_RED_BITMAP         215
#define IDB_RX2_RLL5_RED_BITMAP         216
#define IDB_RX2_RLL1_RED_BITMAP         217
#define IDB_RX_EMPTY_BAR_BITMAP         219
#define IDB_TXBATT1GV_BITMAP            220
#define IDB_TXBATT1GUV_BITMAP           221
#define IDB_BITMAP2                     253
#define IDB_SENTINEL3_BITMAP            253
#define IDD_LOGFILECOPY_DIALOG          255
#define IDB_SYS_WARN_BITMAP             258
#define IDB_SYS_ERROR_BITMAP            259
#define IDB_SYS_INFO_BITMAP             260
#define IDB_GREY_BUTTON_BITMAP          261
#define IDB_RED_BUTTON_BITMAP           262
#define IDB_CHCHARGING_BITMAP           263
#define IDC_SEND_BUTTON                 1000
#define IDC_MAN_CMD_EDIT                1001
#define IDC_IPV4_PORT_EDIT              1002
#define IDC_IPV4_ADDR_EDIT              1003
#define IDC_IPV4_ADDR_STATIC            1004
#define IDC_IPV4_PORT_STATIC            1005
#define IDC_IPV4_STATIC                 1006
#define IDC_SNMP_STATIC                 1007
#define IDC_ETH_RDO                     1008
#define IDC_CONNECTION_CONTROL_GROUP    1009
#define IDC_INFORM_RADIO                1010
#define IDC_INFORM_RESPONSE_STATIC      1011
#define IDC_COMMUNITY_STATIC            1012
#define IDC_HOST_STATIC                 1013
#define IDC_HOST_EDIT                   1014
#define IDC_COMMUNITY_EDIT              1015
#define IDC_RESPONSE_STATIC             1016
#define IDC_RUN_SCRIPT_BUTTON           1018
#define IDC_USB_RDO                     1019
#define IDC_CHOOSE_SCRIPT_BUTTON        1020
#define IDC_SCRIPT_NAME_STATIC          1021
#define IDC_COMMAND_EDIT                1022
#define IDC_OPEN_USB_BUTTON             1023
#define IDC_CLOSE_USB_BUTTON            1024
#define IDC_SEND_USB_BUTTON             1025
#define IDC_COM_PORT_EDIT               1026
#define IDC_IPADDRESS1                  1027
#define IDC_CONNECT_BTN                 1030
#define IDC_CONNECT_BUTTON              1030
#define IDC_MAN_CMD_SEND_BUTTON         1031
#define IDC_QUIT                        1032
#define IDC_AUTOUPDATE_GUI              1034
#define IDC_UPDATE_GUI                  1035
#define IDC_GUI_CONTROL_GROUP           1036
#define IDC_SCRIPT_CONTROL_GROUP        1037
#define IDC_MANUAL_CONTROL_GROUP        1038
#define IDC_REMOTE_LOCAL_CHECK          1043
#define IDC_NETADDRESS1                 1045
#define IDC_GDI_STATIC                  1046
#define IDC_IMGI_STATIC                 1046
#define IDC_IMG_STATIC                  1046
#define IDC_FILE_PROGRESS               1046
#define IDC_GDI_FRAME                   1047
#define IDC_GDI_STATIC2                 1048
#define IDC_TEXT_IP_EDIT                1049
#define IDC_BROWSE                      1050
#define IDC_FILEDIR                     1051
#define IDC_COPY                        1052
#define IDC_TOTAL_BYTES                 1054
#define IDC_PERCENTAGE                  1054
#define IDC_EDIT1                       1056
#define IDC_ABOUT_TEXT                  1056
#define IDC_USBGPIB                     1057
#define IDC_USBSERIAL                   1058
#define IDC_COMBO1                      1060
#define IDC_SERIAL_DROP                 1060
#define S3GDI_TEXT_EDIT                 1627
#define S3GDI_NUM_EDIT                  1628
#define S3GDI_CB                        1629
#define S3GDI_NUM2_EDIT                 1630
#define S3GDI_TIME_EDIT                 1639
#define S3GDI_DATE_EDIT                 1640
#define ID_FILE_QUIT                    32772
#define ID_ABOUT_APP                    32773
#define ID_SETTINGS_OPTIONS             32774
#define ID_AUTOSYNC_TIME                32775
#define ID_SETTINGS_ENABLEMANUALCOMMANDENTRY 32776
#define ID_MANUAL_ENTRY                 32777
#define ID_FILE_DOWNLOADLOGFILE         32778
#define ID_DOWNLOADLOGFILE              32779
#define ID_LOGFILECOPY                  32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        261
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
